Repository math-comp/analysis, pull requests merged in 2023-11, with the labels that each got.

#1076 Radon nikodym cscale
  CHANGELOG_UNRELEASED.md
  theories/charge.v
  theories/lebesgue_integral.v
Labels: TODO: HB port

#1081 Fixes 20231108
  CHANGELOG_UNRELEASED.md
  coq-mathcomp-analysis.opam
  coq-mathcomp-classical.opam
  theories/derive.v
  theories/lebesgue_measure.v
  theories/normedtype.v
  theories/sequences.v
Labels: TODO: HB port

#973 tentative formalization of Vitali's lemma
  CHANGELOG_UNRELEASED.md
  classical/classical_sets.v
  classical/mathcomp_extra.v
  theories/lebesgue_measure.v
  theories/normedtype.v
  theories/topology.v
Labels: enhancement :sparkles:, TODO: HB port

#1085 fixes #1052 (renaming in `sequences.v`)
  CHANGELOG_UNRELEASED.md
  theories/charge.v
  theories/esum.v
  theories/kernel.v
  theories/lebesgue_integral.v
  theories/measure.v
  theories/sequences.v
Labels: renaming/refactoring, TODO: HB port

#1047 expeR
  CHANGELOG_UNRELEASED.md
  classical/functions.v
  theories/exp.v
Labels: TODO: HB port

#1091 fixes #1064
  theories/derive.v
Labels: documentation :memo:, TODO: HB port

#1090 easy lemmas
  CHANGELOG_UNRELEASED.md
  theories/exp.v
  theories/measure.v
Labels: TODO: HB port

#1095 changelog for version 0.6.6
  CHANGELOG.md
  CHANGELOG_UNRELEASED.md
  INSTALL.md
  README.md
  coq-mathcomp-analysis.opam
  coq-mathcomp-classical.opam
Labels: documentation :memo:, TODO: HB port

#834 Alexandroff-Hausdorff Theorem and the Cantor Space
  CHANGELOG_UNRELEASED.md
  _CoqProject
  theories/cantor.v
  theories/topology.v
Labels: TODO: HB port

#1106 Fixes 20231117
  CHANGELOG_UNRELEASED.md
  theories/Make
  theories/cantor.v
  theories/constructive_ereal.v
  theories/exp.v
  theories/topology.v
Labels: TODO: HB port
