Repository math-comp/analysis, pull requests merged in 2023-12, with the labels that each got.

#1112 Adapt to math-comp/math-comp#1131
  theories/kernel.v
Labels: TODO: HB port

#995 Hardy littlewood
  CHANGELOG_UNRELEASED.md
  theories/charge.v
  theories/ereal.v
  theories/lebesgue_integral.v
  theories/lebesgue_measure.v
  theories/normedtype.v
  theories/numfun.v
Labels: TODO: HB port

#1110 ae_eq lemmas
  CHANGELOG_UNRELEASED.md
  theories/lebesgue_integral.v
  theories/measure.v
Labels: TODO: HB port

#1125 more opam keywords (MCA-dev meeting of 2023-12-21)
  coq-mathcomp-analysis.opam
Labels: documentation :memo:

#1124 fixes #1123 (unusable lemma)
  theories/ereal.v
Labels: "bug" :bug:
