Repository math-comp/analysis, pull requests merged in 2023-06, with the labels that each got.

#941 fixes #940 (typo)
  classical/cardinality.v
  classical/classical_sets.v
  classical/fsbigop.v
  classical/functions.v
  classical/set_interval.v
  theories/itv.v
  theories/probability.v
  theories/signed.v
Labels: TODO: HB port

#944 format doc of charge.v
  theories/charge.v
Labels: documentation :memo:, TODO: HB port

#949 remove useless hypothesis
  theories/charge.v
Labels: TODO: HB port

#952 changelog for version 0.6.3
  CHANGELOG.md
  CHANGELOG_UNRELEASED.md
  INSTALL.md
Labels: TODO: HB port

#950 update opam files
  coq-mathcomp-analysis.opam
  coq-mathcomp-classical.opam
Labels: HB only

#958 put all_classical in Make
  _CoqProject
  classical/Make
  classical/all_classical.v
  classical/mathcomp_extra.v
Labels: TODO: HB port

#962 More measure theory helpers
  CHANGELOG_UNRELEASED.md
  theories/lebesgue_integral.v
  theories/lebesgue_measure.v
  theories/measure.v
  theories/real_interval.v
  theories/topology.v
Labels: TODO: HB port

#915 Smallest filter
  CHANGELOG_UNRELEASED.md
  classical/classical_sets.v
  classical/functions.v
  theories/topology.v
Labels: enhancement :sparkles:, TODO: HB port

#964 Egorov's theorem
  CHANGELOG_UNRELEASED.md
  theories/lebesgue_measure.v
Labels: TODO: HB port

#961 fixes #960
  CHANGELOG_UNRELEASED.md
  classical/boolp.v
Labels: TODO: HB port

#953 add measurable_minr
  CHANGELOG_UNRELEASED.md
  classical/classical_sets.v
  classical/mathcomp_extra.v
  theories/charge.v
  theories/lebesgue_measure.v
Labels: TODO: HB port

#956 Coqdoc
  Makefile.common
Labels: TODO: HB port

#939 minor fixes and additions to `exp.v`
  CHANGELOG_UNRELEASED.md
  theories/exp.v
Labels: enhancement :sparkles:, TODO: HB port

#959 fix make doc
  Makefile.common
Labels: TODO: HB port
