Repository math-comp/analysis, pull requests merged in 2023-10, with the labels that each got.

#1027 Lemma gt0_ltr_powR
  CHANGELOG_UNRELEASED.md
  theories/exp.v
Labels: enhancement :sparkles:, TODO: HB port

#1011 Convexity of powR
  CHANGELOG_UNRELEASED.md
  classical/mathcomp_extra.v
  theories/convex.v
  theories/exp.v
  theories/hoelder.v
  theories/lebesgue_integral.v
Labels: enhancement :sparkles:, TODO: HB port

#1033 Readme 20231002
  README.md
Labels: TODO: HB port

#1034 add link to coqdoc
  README.md
Labels: TODO: HB port

#1036 bump coq version in opam
  coq-mathcomp-classical.opam
Labels: TODO: HB port

#1050 fixes #1049
  theories/lebesgue_integral.v
Labels: TODO: HB port

#1059 Adapt to https://github.com/coq/coq/pull/18014
  theories/landau.v
Labels: TODO: HB port

#1058 negligible_bigcup
  CHANGELOG_UNRELEASED.md
  theories/measure.v
Labels: enhancement :sparkles:, TODO: HB port

#1057 fixes #1056
  CHANGELOG_UNRELEASED.md
  theories/lebesgue_integral.v
Labels: TODO: HB port

#1062 New notations of negative/positive_set
  CHANGELOG_UNRELEASED.md
  theories/charge.v
Labels: enhancement :sparkles:, TODO: HB port

#677 Lebesgue Stieltjes measure
  CHANGELOG_UNRELEASED.md
  _CoqProject
  theories/Make
  theories/constructive_ereal.v
  theories/ereal.v
  theories/lebesgue_integral.v
  theories/lebesgue_measure.v
  theories/lebesgue_stieltjes_measure.v
  theories/probability.v
  theories/reals.v
Labels: enhancement :sparkles:

#1070 rm Idioms
  CONTRIBUTING.md
Labels: TODO: HB port

#1068 fixes #1051 (rename `lim_sup` -> `limn_sup`)
  CHANGELOG_UNRELEASED.md
  CONTRIBUTING.md
  classical/cardinality.v
  classical/classical_sets.v
  classical/fsbigop.v
  theories/charge.v
  theories/constructive_ereal.v
  theories/derive.v
  theories/kernel.v
  theories/lebesgue_integral.v
  theories/lebesgue_measure.v
  theories/measure.v
  theories/normedtype.v
  theories/sequences.v
  theories/topology.v
Labels: TODO: HB port
