Repository math-comp/analysis, pull requests merged in 2023-05, with the labels that each got.

#924 rm dup emeasurable_funN
  CHANGELOG_UNRELEASED.md
  theories/lebesgue_integral.v
Labels: TODO: HB port

#914 uniqueness of RN derivatives up ae eq
  CHANGELOG_UNRELEASED.md
  classical/classical_sets.v
  theories/lebesgue_integral.v
  theories/real_interval.v
Labels: enhancement :sparkles:, TODO: HB port

#918 Covariance
  CHANGELOG_UNRELEASED.md
  classical/functions.v
  theories/constructive_ereal.v
  theories/derive.v
  theories/ereal.v
  theories/lebesgue_integral.v
  theories/probability.v
Labels: TODO: HB port

#928 remove duplicated information about nix
  NIX.md
  README.md
Labels: documentation :memo:, TODO: HB port

#929 measurable_fun lemmas renaming
  CHANGELOG_UNRELEASED.md
  theories/kernel.v
  theories/lebesgue_integral.v
  theories/lebesgue_measure.v
  theories/measure.v
  theories/probability.v
Labels: renaming/refactoring, TODO: HB port

#920 Cantelli
  CHANGELOG_UNRELEASED.md
  theories/probability.v
Labels: TODO: HB port

#932 Lock integrable
  CHANGELOG_UNRELEASED.md
  theories/lebesgue_integral.v
  theories/probability.v
Labels: TODO: HB port

#919 Covariance inequality
  CHANGELOG_UNRELEASED.md
  classical/mathcomp_extra.v
  theories/probability.v
Labels: TODO: HB port
