Repository math-comp/analysis, pull requests merged in 2023-07, with the labels that each got.

#968 Simple functions are dense in L1
  CHANGELOG_UNRELEASED.md
  theories/lebesgue_integral.v
Labels: TODO: HB port

#974 minor generalizations, additions, fixes
  CHANGELOG_UNRELEASED.md
  classical/classical_sets.v
  classical/mathcomp_extra.v
  theories/charge.v
  theories/lebesgue_integral.v
  theories/measure.v
  theories/sequences.v
Labels: enhancement :sparkles:, renaming/refactoring, TODO: HB port

#966 Lusin
  CHANGELOG_UNRELEASED.md
  theories/lebesgue_integral.v
  theories/measure.v
  theories/topology.v
Labels: TODO: HB port

#977 minor generalizations measure -> content
  CHANGELOG_UNRELEASED.md
  theories/kernel.v
  theories/measure.v
  theories/probability.v
Labels: enhancement :sparkles:, TODO: HB port

#980 fixes #979 (my_ball_le from local lemme to `Let`)
  CHANGELOG_UNRELEASED.md
  theories/topology.v
Labels: TODO: HB port

#978 Zorn lemma for inclusion
  CHANGELOG_UNRELEASED.md
  classical/classical_sets.v
Labels: enhancement :sparkles:, TODO: HB port

#986 extended distance
  CHANGELOG_UNRELEASED.md
  classical/boolp.v
  theories/constructive_ereal.v
  theories/normedtype.v
  theories/reals.v
  theories/topology.v
Labels: TODO: HB port

#971 Tietze's theorem
  CHANGELOG_UNRELEASED.md
  theories/numfun.v
  theories/real_interval.v
  theories/sequences.v
  theories/topology.v
Labels: TODO: HB port

#985 minor generalizations, renaming
  CHANGELOG_UNRELEASED.md
  theories/lebesgue_integral.v
  theories/lebesgue_measure.v
  theories/normedtype.v
  theories/probability.v
  theories/reals.v
  theories/sequences.v
Labels: TODO: HB port

#997 Fixes 994
  CHANGELOG_UNRELEASED.md
  classical/classical_sets.v
  theories/lebesgue_integral.v
  theories/sequences.v
Labels: TODO: HB port

#989 fixes #988 (`bigcup_bigcup`)
  CHANGELOG_UNRELEASED.md
  classical/classical_sets.v
  theories/measure.v
Labels: TODO: HB port

#991 closed_bigcup
  CHANGELOG_UNRELEASED.md
  theories/topology.v
Labels: TODO: HB port

#996 Int signed instances
  CHANGELOG_UNRELEASED.md
  theories/signed.v
Labels: TODO: HB port
