Repository math-comp/analysis, pull requests merged in 2023-04, with the labels that each got.

#889 typo in filename
  .github/pull_request_template.md
Labels: TODO: HB port

#891 power function for extended real numbers
  CHANGELOG_UNRELEASED.md
  theories/exp.v
  theories/lebesgue_measure.v
  theories/measure.v
Labels: TODO: HB port

#890 redirect to tools
  .github/pull_request_template.md
  etc/changes.awk
  etc/changes.sh
Labels: TODO: HB port

#875 conv -> line_path
  CHANGELOG_UNRELEASED.md
  classical/set_interval.v
Labels: renaming/refactoring, TODO: HB port

#886 Cantor Space Theory: zero dimensional and totally disconnected
  CHANGELOG_UNRELEASED.md
  theories/topology.v
Labels: enhancement :sparkles:, TODO: HB port

#857 Uniform spaces are sups of pseudometrics
  CHANGELOG_UNRELEASED.md
  theories/topology.v
Labels: TODO: HB port

#893 Cantor misc
  CHANGELOG_UNRELEASED.md
  theories/topology.v
Labels: enhancement :sparkles:, TODO: HB port

#516 Probability
  CHANGELOG_UNRELEASED.md
  _CoqProject
  theories/constructive_ereal.v
  theories/ereal.v
  theories/lebesgue_integral.v
  theories/lebesgue_measure.v
  theories/probability.v
Labels: enhancement :sparkles:, TODO: HB port

#873 Convex exp
  CHANGELOG_UNRELEASED.md
  _CoqProject
  classical/set_interval.v
  theories/Make
  theories/convex.v
  theories/derive.v
  theories/exp.v
  theories/itv.v
  theories/normedtype.v
  theories/realfun.v
Labels: enhancement :sparkles:, TODO: HB port

#777 Hahn decomposition theorem
  CHANGELOG_UNRELEASED.md
  _CoqProject
  classical/classical_sets.v
  classical/mathcomp_extra.v
  theories/Make
  theories/charge.v
  theories/constructive_ereal.v
  theories/lebesgue_integral.v
  theories/numfun.v
  theories/sequences.v
Labels: enhancement :sparkles:, TODO: HB port

#833 clarify status of lemmas in altreals
  CHANGELOG_UNRELEASED.md
  theories/altreals/distr.v
  theories/altreals/realsum.v
Labels: documentation :memo:, TODO: HB port

#907 fixes #901
  CHANGELOG_UNRELEASED.md
  theories/derive.v
  theories/measure.v
  theories/normedtype.v
Labels: enhancement :sparkles:, TODO: HB port

#910 fixes #909
  CHANGELOG_UNRELEASED.md
  theories/derive.v
Labels: renaming/refactoring, TODO: HB port

#913 generalization of `measurable_funU`
  CHANGELOG_UNRELEASED.md
  theories/measure.v
Labels: enhancement :sparkles:, TODO: HB port

#911 eq_seriesl
  CHANGELOG_UNRELEASED.md
  theories/sequences.v
Labels: enhancement :sparkles:, TODO: HB port
