Repository math-comp/analysis, pull requests merged in 2023-03, with the labels that each got.

#858 generalize emeasurable_itv_* lemmas
  CHANGELOG_UNRELEASED.md
  theories/lebesgue_integral.v
  theories/lebesgue_measure.v
Labels: kind: enhancement

#863 fix and strengthen eq_bigmax and eq_bigmin
  CHANGELOG_UNRELEASED.md
  classical/mathcomp_extra.v
Labels: kind: "bug"

#869 Itv
  CHANGELOG_UNRELEASED.md
  _CoqProject
  theories/itv.v
Labels: kind: enhancement

#881 factor out ae proofs
  CHANGELOG_UNRELEASED.md
  theories/lebesgue_integral.v
  theories/measure.v
Labels: kind: enhancement

#877 fubini for s-finite measures
  CHANGELOG_UNRELEASED.md
  theories/lebesgue_integral.v
Labels: enhancement :sparkles:

#874 Issues 20230314
  CHANGELOG_UNRELEASED.md
  classical/functions.v
  theories/realfun.v
  theories/topology.v
Labels: documentation :memo:, renaming/refactoring, TODO: HB port

#841 Fix #839
  theories/topology.v
Labels: "bug" :bug:, TODO: HB port

#876 gen exp_fun
  CHANGELOG_UNRELEASED.md
  theories/exp.v
  theories/lebesgue_measure.v
Labels: "bug" :bug:, TODO: HB port
