Repository math-comp/analysis, pull requests merged in 2024-01, with the labels that each got.

#1129 rm dup lemmas
  CHANGELOG_UNRELEASED.md
  theories/forms.v
Labels: TODO: HB port

#1083 Radon-Nikodym chain rule
  CHANGELOG_UNRELEASED.md
  theories/charge.v
  theories/constructive_ereal.v
  theories/lebesgue_integral.v
  theories/measure.v
  theories/sequences.v
Labels: TODO: HB port

#1130 format doc
  CHANGELOG_UNRELEASED.md
  classical/mathcomp_extra.v
  theories/topology.v
Labels: documentation :memo:, TODO: HB port

#1116 restrain the scope of measurable args
  theories/lebesgue_measure.v
  theories/measure.v
Labels: enhancement :sparkles:, TODO: HB port

#1121 isolate the theory of lime_sup
  CHANGELOG_UNRELEASED.md
  theories/constructive_ereal.v
  theories/lebesgue_integral.v
  theories/lebesgue_measure.v
  theories/normedtype.v
  theories/realfun.v
  theories/sequences.v
  theories/topology.v
Labels: enhancement :sparkles:, TODO: HB port

#1136 helper lemmas for contra (PR #1119)
  CHANGELOG_UNRELEASED.md
  classical/boolp.v
Labels: TODO: HB port

#1108 minimal changes to documentation to test coq2html
  classical/boolp.v
  classical/cardinality.v
  classical/classical_sets.v
  classical/fsbigop.v
  classical/functions.v
  classical/mathcomp_extra.v
  classical/set_interval.v
  theories/Rstruct.v
  theories/cantor.v
  theories/charge.v
  theories/constructive_ereal.v
  theories/convex.v
  theories/derive.v
  theories/ereal.v
  theories/esum.v
  theories/exp.v
  theories/forms.v
  theories/hoelder.v
  theories/itv.v
  theories/kernel.v
  theories/landau.v
  theories/lebesgue_integral.v
  theories/lebesgue_measure.v
  theories/lebesgue_stieltjes_measure.v
  theories/measure.v
  theories/normedtype.v
  theories/nsatz_realtype.v
  theories/numfun.v
  theories/probability.v
  theories/prodnormedzmodule.v
  theories/real_interval.v
  theories/realfun.v
  theories/reals.v
  theories/sequences.v
  theories/signed.v
  theories/summability.v
  theories/topology.v
  theories/trigo.v
Labels: experiment :test_tube:, documentation :memo:, TODO: HB port

#1142 upd misc/uniform_bigO.v
  theories/misc/uniform_bigO.v
Labels: TODO: HB port

#1143 Changelog067
  CHANGELOG.md
  CHANGELOG_UNRELEASED.md
  INSTALL.md
  README.md
Labels: TODO: HB port

#1146 add HB instances
  CHANGELOG_UNRELEASED.md
  theories/lebesgue_integral.v
  theories/lebesgue_measure.v
  theories/lebesgue_stieltjes_measure.v
Labels: enhancement :sparkles:

#1148 adapt to change in coq2html
  classical/boolp.v
  classical/cardinality.v
  classical/classical_sets.v
  classical/fsbigop.v
  classical/functions.v
  classical/mathcomp_extra.v
  classical/set_interval.v
  theories/Rstruct.v
  theories/cantor.v
  theories/charge.v
  theories/constructive_ereal.v
  theories/convex.v
  theories/derive.v
  theories/ereal.v
  theories/esum.v
  theories/exp.v
  theories/forms.v
  theories/hoelder.v
  theories/itv.v
  theories/kernel.v
  theories/landau.v
  theories/lebesgue_integral.v
  theories/lebesgue_measure.v
  theories/lebesgue_stieltjes_measure.v
  theories/measure.v
  theories/normedtype.v
  theories/nsatz_realtype.v
  theories/numfun.v
  theories/probability.v
  theories/prodnormedzmodule.v
  theories/real_interval.v
  theories/realfun.v
  theories/reals.v
  theories/sequences.v
  theories/signed.v
  theories/summability.v
  theories/topology.v
  theories/trigo.v
Labels: documentation :memo:, TODO: HB port

#1147 generalizations
  CHANGELOG_UNRELEASED.md
  theories/realfun.v
Labels: enhancement :sparkles:, TODO: HB port

#926 Curry is continuous
  CHANGELOG_UNRELEASED.md
  theories/topology.v
Labels: TODO: HB port

#1119 contra tactic and helper lemmas (in boolp.v)
  CHANGELOG_UNRELEASED.md
  _CoqProject
  classical/Make
  classical/all_classical.v
  classical/contra.v
Labels: TODO: HB port

#1158 changelog for version 0.7.0
  CHANGELOG.md
  CHANGELOG_UNRELEASED.md
  INSTALL.md
  README.md
Labels: TODO: HB port

#1155 fixes #1006
  CHANGELOG_UNRELEASED.md
  theories/lebesgue_measure.v
  theories/lebesgue_stieltjes_measure.v
Labels: "bug" :bug:, TODO: HB port
