Repository math-comp/analysis, pull requests merged in 2024-04, with the labels that each got.

#1204 fixes #1203
  CHANGELOG_UNRELEASED.md
  theories/charge.v
  theories/constructive_ereal.v
  theories/ereal.v
  theories/esum.v
  theories/lebesgue_integral.v
  theories/lebesgue_measure.v
  theories/lebesgue_stieltjes_measure.v
  theories/measure.v
  theories/normedtype.v
  theories/realfun.v
  theories/sequences.v
Labels: enhancement :sparkles:

#1199 fixes #981 (`sub_additive` vs `subadditive`)
  CHANGELOG_UNRELEASED.md
  classical/classical_sets.v
  theories/charge.v
  theories/hoelder.v
  theories/kernel.v
  theories/lebesgue_integral.v
  theories/lebesgue_measure.v
  theories/lebesgue_stieltjes_measure.v
  theories/measure.v
  theories/sequences.v
Labels: renaming/refactoring

#1196 Bigcap series addn
  CHANGELOG_UNRELEASED.md
  classical/classical_sets.v
  theories/sequences.v
Labels: enhancement :sparkles:

#1207 integrableM lemmas
  CHANGELOG_UNRELEASED.md
  theories/lebesgue_integral.v
Labels: enhancement :sparkles:

#1210 Measure 20240416
  CHANGELOG_UNRELEASED.md
  theories/measure.v
  theories/probability.v
Labels: enhancement :sparkles:, documentation :memo:, renaming/refactoring
