Repository math-comp/analysis, pull requests merged in 2024-12, with the labels that each got.

#1418 prod notation for ereal and lemmas
  CHANGELOG_UNRELEASED.md
  reals/constructive_ereal.v
Labels: enhancement :sparkles:

#1420 generalize the return type of RVs
  CHANGELOG_UNRELEASED.md
  theories/probability.v
Labels: enhancement :sparkles:

#1426 rename homotopy_theory/path.v
  CHANGELOG_UNRELEASED.md
  _CoqProject
  theories/Make
  theories/homotopy_theory/continuous_path.v
  theories/homotopy_theory/homotopy.v
Labels: "bug" :bug:

#1396 convergence of a real function
  CHANGELOG_UNRELEASED.md
  theories/realfun.v
Labels: enhancement :sparkles:

#1434 add lemma measurable_powRr
  CHANGELOG_UNRELEASED.md
  theories/lebesgue_measure.v
Labels: enhancement :sparkles:

#1438 factorize code about powerset sigma-algebras
  CHANGELOG_UNRELEASED.md
  theories/measure.v
Labels: renaming/refactoring :wrench:

#1441 Accelerated Analysis
  theories/convex.v
  theories/derive.v
  theories/lebesgue_integral.v
  theories/measure.v
  theories/probability.v
  theories/realfun.v
  theories/trigo.v
Labels: enhancement :sparkles:

#1443 minor generalization and renaming
  CHANGELOG_UNRELEASED.md
  classical/classical_sets.v
  theories/lebesgue_integral.v
  theories/measure.v
  theories/numfun.v
Labels: renaming/refactoring :wrench:
