Repository math-comp/analysis, pull requests merged in 2024-09, with the labels that each got.

#334 Banachsteinhaus
  CHANGELOG_UNRELEASED.md
  theories/normedtype.v
  theories/sequences.v
Labels: enhancement :sparkles:

#1314 fixes #1313 and moves Egorov
  theories/lebesgue_integral.v
  theories/lebesgue_measure.v
  theories/normedtype.v
  theories/topology.v
Labels: documentation :memo:

#1312 Unpointed topologies with no backwards compatibility
  CHANGELOG_UNRELEASED.md
  theories/Rstruct.v
  theories/cantor.v
  theories/function_spaces.v
  theories/normedtype.v
  theories/sequences.v
  theories/topology.v
Labels: renaming/refactoring :wrench:

#1306 lemmas about measurable from PR prob_lang
  CHANGELOG_UNRELEASED.md
  theories/lebesgue_measure.v
  theories/measure.v
Labels: enhancement :sparkles:

#1266 integration by parts
  CHANGELOG_UNRELEASED.md
  classical/set_interval.v
  theories/ftc.v
  theories/lebesgue_integral.v
  theories/normedtype.v
  theories/realfun.v
  theories/topology.v
Labels: enhancement :sparkles:
