Repository math-comp/analysis, pull requests merged in 2024-10, with the labels that each got.

#1330 fixes #1329 (`maxeMr`)
  CHANGELOG_UNRELEASED.md
  theories/constructive_ereal.v
  theories/lebesgue_integral.v
  theories/numfun.v
Labels: enhancement :sparkles:

#1321 lexical ordering over nats
  CHANGELOG_UNRELEASED.md
  _CoqProject
  classical/Make
  classical/all_classical.v
  classical/classical_orders.v
Labels: enhancement :sparkles:

#1324 separating filters
  CHANGELOG_UNRELEASED.md
  _CoqProject
  classical/Make
  classical/all_classical.v
  classical/boolp.v
  classical/filter.v
  classical/mathcomp_extra.v
  theories/ereal.v
  theories/normedtype.v
  theories/topology.v
Labels: "bug" :bug:

#1337 weaken expR_ge1Dx
  CHANGELOG_UNRELEASED.md
  theories/exp.v
Labels: enhancement :sparkles:

#1338 Splitting Topology part 3: Separation axioms
  CHANGELOG_UNRELEASED.md
  _CoqProject
  theories/Make
  theories/cantor.v
  theories/function_spaces.v
  theories/normedtype.v
  theories/separation_axioms.v
  theories/topology.v
Labels: enhancement :sparkles:

#1341 minor gen and addition
  CHANGELOG_UNRELEASED.md
  theories/derive.v
Labels: enhancement :sparkles:

#1328 corollary to Vitali's theorem
  CHANGELOG_UNRELEASED.md
  theories/constructive_ereal.v
  theories/lebesgue_measure.v
  theories/normedtype.v
  theories/sequences.v
Labels: enhancement :sparkles:

#1252 generalize lime_sup_ge0
  CHANGELOG_UNRELEASED.md
  classical/filter.v
  theories/lebesgue_integral.v
  theories/normedtype.v
  theories/realfun.v
  theories/topology.v
Labels: renaming/refactoring :wrench:

#1294 change of variables by nondecreasing/nonincreasing function
  CHANGELOG_UNRELEASED.md
  theories/ftc.v
  theories/lebesgue_integral.v
  theories/lebesgue_measure.v
  theories/measure.v
  theories/normedtype.v
Labels: enhancement :sparkles:, experiment :test_tube:

#1353 rm dep on topo and ereal from altreals
  theories/altreals/distr.v
  theories/altreals/realseq.v
  theories/altreals/realsum.v
Labels: renaming/refactoring :wrench:

#1331 completely regular spaces and locally compact implies uniform
  CHANGELOG_UNRELEASED.md
  _CoqProject
  classical/filter.v
  theories/Make
  theories/normedtype.v
  theories/separation_axioms.v
  theories/topology_theory/one_point_compactification.v
  theories/topology_theory/topology.v
Labels: enhancement :sparkles:
