Repository math-comp/analysis, pull requests merged in 2025-09, with the labels that each got.

#1715 add lemma lt0_adde
  CHANGELOG_UNRELEASED.md
  reals/constructive_ereal.v
Labels: enhancement :sparkles:

#1710 CI: :memo: :construction_worker: `make html` generate hierarchy graph
  .github/workflows/generate_docs.yml
  Makefile.common
  etc/rocqnavi_generate-hierarchy-graph.sh
  etc/rocqnavi_index-blacklist
Labels: documentation :memo:

#1725 fixes #1627
  theories/normedtype_theory/num_normedtype.v
Labels: build/continuous integration :gear:
