Repository math-comp/analysis, pull requests merged in 2025-04, with the labels that each got.

#1540 add continuous_under_integral
  CHANGELOG_UNRELEASED.md
  _CoqProject
  classical/mathcomp_extra.v
  reals/interval_inference.v
  theories/Make
  theories/ftc.v
  theories/lebesgue_integral.v
  theories/lebesgue_integral_theory/lebesgue_Rintegral.v
  theories/lebesgue_integral_theory/lebesgue_integrable.v
  theories/lebesgue_integral_theory/lebesgue_integral.v
  theories/lebesgue_integral_theory/lebesgue_integral_approximation.v
  theories/lebesgue_integral_theory/lebesgue_integral_definition.v
  theories/lebesgue_integral_theory/lebesgue_integral_differentiation.v
  theories/lebesgue_integral_theory/lebesgue_integral_dominated_convergence.v
  theories/lebesgue_integral_theory/lebesgue_integral_fubini.v
  theories/lebesgue_integral_theory/lebesgue_integral_monotone_convergence.v
  theories/lebesgue_integral_theory/lebesgue_integral_nonneg.v
  theories/lebesgue_integral_theory/lebesgue_integral_under.v
  theories/lebesgue_integral_theory/simple_functions.v
  theories/lebesgue_measure.v
  theories/numfun.v
  theories/topology_theory/topology_structure.v
Labels: enhancement :sparkles:, renaming/refactoring :wrench:

#1556 fixes #1427
  CHANGELOG_UNRELEASED.md
  classical/boolp.v
  classical/classical_sets.v
  theories/measurable_realfun.v
  theories/topology_theory/topology_structure.v
Labels: renaming/refactoring :wrench:

#1559 fixes #1510
  CHANGELOG_UNRELEASED.md
  classical/classical_sets.v
  theories/measure.v
  theories/topology_theory/pseudometric_structure.v
Labels: documentation :memo:

#1557 fixes #1458
  theories/derive.v
  theories/normedtype.v
  theories/separation_axioms.v
  theories/sequences.v
  theories/topology_theory/compact.v
  theories/topology_theory/matrix_topology.v
  theories/topology_theory/product_topology.v
  theories/topology_theory/pseudometric_structure.v
  theories/topology_theory/subspace_topology.v
  theories/topology_theory/topology_structure.v
  theories/topology_theory/uniform_structure.v
Labels: renaming/refactoring :wrench:

#1560 fixes #1496
  theories/forms.v
  theories/normedtype.v
Labels: "bug" :bug:

#1558 minor additions
  CHANGELOG_UNRELEASED.md
  reals/constructive_ereal.v
  theories/lebesgue_integral_theory/lebesgue_integral_fubini.v
  theories/measure.v
  theories/sequences.v
Labels: enhancement :sparkles:

#1562 fixes #1514 (`prod` vs. `pair`)
  CHANGELOG_UNRELEASED.md
  theories/measure.v
Labels: renaming/refactoring :wrench:

#1569 document weak_topology as initial topology
  theories/topology_theory/weak_topology.v
Labels: documentation :memo:

#1573 fixes #1268 (rm `at_point`)
  CHANGELOG_UNRELEASED.md
  classical/filter.v
  theories/derive.v
  theories/topology_theory/topology_structure.v
Labels: renaming/refactoring :wrench:

#1444 finite transition kernels
  CHANGELOG_UNRELEASED.md
  theories/kernel.v
  theories/measure.v
  theories/numfun.v
Labels: enhancement :sparkles:

#1544 split normedtype.v
  CHANGELOG_UNRELEASED.md
  _CoqProject
  classical/set_interval.v
  theories/Make
  theories/ftc.v
  theories/lebesgue_integral_theory/lebesgue_integral_fubini.v
  theories/lebesgue_measure.v
  theories/lebesgue_stieltjes_measure.v
  theories/measurable_realfun.v
  theories/normedtype.v
  theories/normedtype_theory/complete_normed_module.v
  theories/normedtype_theory/ereal_normedtype.v
  theories/normedtype_theory/matrix_normedtype.v
  theories/normedtype_theory/normed_module.v
  theories/normedtype_theory/normedtype.v
  theories/normedtype_theory/num_normedtype.v
  theories/normedtype_theory/pseudometric_normed_Zmodule.v
  theories/normedtype_theory/urysohn.v
  theories/normedtype_theory/vitali_lemma.v
  theories/sequences.v
  theories/topology_theory/matrix_topology.v
  theories/topology_theory/num_topology.v
  theories/topology_theory/separation_axioms.v
  theories/tvs.v
Labels: renaming/refactoring :wrench:

#1580 rename cvgeMl and cvgeMr
  CHANGELOG_UNRELEASED.md
  theories/charge.v
  theories/lebesgue_integral_theory/lebesgue_integral_definition.v
  theories/measure.v
  theories/normedtype_theory/normed_module.v
  theories/realfun.v
Labels: renaming/refactoring :wrench:

#1564 integrability of normal_pdf
  CHANGELOG_UNRELEASED.md
  classical/filter.v
  theories/gauss_integral.v
  theories/lebesgue_integral_theory/lebesgue_integrable.v
  theories/lebesgue_integral_theory/lebesgue_integral_approximation.v
  theories/normedtype_theory/normed_module.v
  theories/numfun.v
  theories/probability.v
  theories/sequences.v
  theories/topology_theory/topology_structure.v
Labels: enhancement :sparkles:

#1561 variants of deriveMr and deriveMl
  CHANGELOG_UNRELEASED.md
  theories/derive.v
  theories/gauss_integral.v
Labels: enhancement :sparkles:

#1563 generalizations of derive incr/decr lemmas
  CHANGELOG_UNRELEASED.md
  theories/derive.v
  theories/measure.v
  theories/normedtype_theory/ereal_normedtype.v
  theories/normedtype_theory/num_normedtype.v
  theories/normedtype_theory/pseudometric_normed_Zmodule.v
Labels: enhancement :sparkles:

#1587 fixes #1586
  CHANGELOG_UNRELEASED.md
  theories/pi_irrational.v
Labels: "bug" :bug:

#1588 typos
  theories/topology_theory/pseudometric_structure.v
  theories/topology_theory/separation_axioms.v
Labels: documentation :memo:

#1583 generic lemmas from the prob_lang PR
  CHANGELOG_UNRELEASED.md
  classical/classical_sets.v
  classical/mathcomp_extra.v
  reals/constructive_ereal.v
  theories/ftc.v
  theories/kernel.v
  theories/measure.v
  theories/probability.v
Labels: enhancement :sparkles:

#1592 lemma extracted from the sampling branch to help rebasing
  CHANGELOG_UNRELEASED.md
  theories/lebesgue_integral_theory/lebesgue_integral_approximation.v
Labels: enhancement :sparkles:

#1597 Measurable realfun 20250430
  CHANGELOG_UNRELEASED.md
  _CoqProject
  theories/Make
  theories/charge.v
  theories/exp.v
  theories/ftc.v
  theories/lebesgue_integral_theory/lebesgue_Rintegral.v
  theories/lebesgue_integral_theory/lebesgue_integrable.v
  theories/lebesgue_integral_theory/lebesgue_integral.v
  theories/lebesgue_integral_theory/lebesgue_integral_differentiation.v
  theories/lebesgue_integral_theory/lebesgue_integral_dominated_convergence.v
  theories/lebesgue_integral_theory/lebesgue_integral_fubini.v
  theories/lebesgue_integral_theory/lebesgue_integral_monotone_convergence.v
  theories/lebesgue_integral_theory/lebesgue_integral_nonneg.v
  theories/lebesgue_integral_theory/measurable_fun_approximation.v
Labels: enhancement :sparkles:
